### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by sailinf** [WPprodigy/woocommerce-external-product-embed#10]
Hi Caleb. I took a second shot at testing your plugin together with a multilingual Woo store. Result: partial success and partial disaster ;-).

Success: Apparently something has happened with the Woo Rest API as I could now access products also in other languages than site default (which was the initial problem I had). Happy, happy!

However, I managed to do this exactly one time, after that the remote page (where your plugin is installed) totally broke down. What exactly happens is that the page HTML renders up to your plugin but no further and the page totally freezes (seems to Javascipt is loaded either, for instance to top admin bar is not shown on the page. The page can be seen here: http://sail-in-finland.info/product-test/.

At the point where the HTML stops is your shortcode.

Site is WP 4.4.2, Woo not installed, remote site is WP 4.4.2 also and WC 2.5, both with Comet cache. I've tested also with the Cache cleared, does not seem to be related to that. I've reset the REST credentials a number of times, the remote site does not see the REST call so looks like the problem is on the side the plugin?

**Comment by WPprodigy** [comment]
Hey @sailinf,

Hmm, that is strange. Could you try clearing the transients in the plugin settings and testing again?

If it still isn't working, then enable debug mode and let me know what errors you see: https://codex.wordpress.org/WP_DEBUG

**Comment by sailinf** [comment]
I have done:
- turned off cache
- deleted expired transients
- enabled debug

Chrome console shows nothing, debug shows nothing, page just "dies in midflight"

This is the complete code on the page:
-------
Embed products below this line:
[external_product id="1357"]
End

I'd so much like this to work, anything I can do to help you solve the prob? 

Håkan

**Comment by WPprodigy** [comment]
Is `WP_DEBUG_DISPLAY` enabled? Could you maybe also try turning on `WP_DEBUG_LOG` and see if there are any errors in the log? Make sure there are no other WP_DEBUG calls in your config file below where you are currently editing it as well.

If the page is dying like that, then there must be a fatal error occurring somewhere.

**Comment by sailinf** [comment]
Yes, display was enabled (it is the default, right?) and DEBUG_LOG was explicitely enabled and no file was created. 

??

**Comment by WPprodigy** [comment]
Need more info on this one, can't solve without being able to replicate or with more detailed error codes.
