### ISSUE TITLE
Filter by category or tag

### ISSUE THREAD

**Issue by danicasati** [WPprodigy/woocommerce-external-product-embed#11]
Hi.
Is it possible to add shortcodes in order to add external products filtering by product category or product tag?

**Comment by WPprodigy** [comment]
Would need to add a custom API call similar to this: https://github.com/WPprodigy/woocommerce-external-product-embed/blob/master/classes/class-woocommerce-external-product-embed-transients.php#L73, but filtering by category or tag as well.
