### ISSUE TITLE
Feature Request - More options for displaying products

### ISSUE THREAD

**Issue by gilesytheking** [WPprodigy/woocommerce-external-product-embed#12]
I have been looking for a plugin like this for ages, so that I can display products from my store to other sites that I run. I have managed to get it working on my site and it works great. I have found however that the [external_product] shortcode only works when i specify a product id, which is great for promoting a specific product or products. I have a lot of products and want to have more options for displaying different types of products from my woo store.

Is there a way to add the following features to give more options for displaying products?
- Display random products from the woo store,
- Display products from a specific category
- Display products with reviews / specific rating
- Display on sale products
- Don't display out of stock products.

**Comment by WPprodigy** [comment]
Currently, the only option other than individual ID's is the `[recent_external_products]` shortcode where you can display recent products.

It's tricky if you get to broad on what products you want. For example, to get random products - I'd need to first pull all products from the original site and then pick a few random IDs. This would be terribly resource heavy and slow. The same applies to looking at all products and only pulling on-sale ones, etc.

There are a lot more options with the latest version of the rest api though: http://woothemes.github.io/woocommerce-rest-api-docs/#list-all-products. Looks like I can pull products based on category now. 

I'll look into adding some more options.

**Comment by WPprodigy** [comment]
The next update will have lots of cool stuff. It has one powerful shortcode that can combine all those things.

- Display products from a specific category or multiple categories
- Display on sale products
- Display recent products
- Display featured products
- Display products by sku or ID

- You can change the orderby, order, status, etc.

And all of them can be combined. So for example, this shortcode:
`[wcepe_products category='19,28' featured=true]` it will display featured products that are in those two categories.

I'll update the readme by release with more details.
