### ISSUE TITLE
Feature: Product Category Shortcode

### ISSUE THREAD

**Issue by sunshinephotocart** [WPprodigy/woocommerce-external-product-embed#13]
Our use is constantly timing out. I imagine it is because we are trying to load 20+ products via single embed code. The best solution I imagine would be a way to get an entire category instead of doing products individually, this would reduce the query to the remote server significantly than 20+ separate API requests.

**Comment by WPprodigy** [comment]
If I remember correctly, I couldn't do it by category with the version of the API I used when I made this. But should be able to do it now.

**Comment by sunshinephotocart** [comment]
Are you still working on this project or is it something that I would need to fork and figure out on my own?

**Comment by WPprodigy** [comment]
Ehh, I have some plans for it - but not much time. Probably best to fork it if you need it for a project soon.

I'd be happy to help though if you have questions. Feel free to ping me on the make WordPress slack.

**Comment by dild2001** [comment]
Hello there !!
Is there work going on for bringing the Product Category Shortcode ?

**Comment by WPprodigy** [comment]
Will be possible in the next update. Requires WooCommerce 3.0+.

I opted to use one, powerful, shortcode this time around. `[wcepe_products]` will be able to do lots of things, including display products from a one category, or more :)

`[wcepe_products cateogory='19,28' per_page="20"]`

Can even show only on-sale products from those category, and/or only featured products.

`[wcepe_products cateogory='19,28' featured=true]`

I'll have the readme updating by release.
