### ISSUE TITLE
Broken on Woocommerce 3.x

### ISSUE THREAD

**Issue by danicasati** [WPprodigy/woocommerce-external-product-embed#14]
Hi.
The plugin is broken on Woocommerce 3 version.

Diaplays an error 500 and doesn't render post content.
Coudl you fix it?

**Comment by danicasati** [comment]
Could you verify this issue?

**Comment by WPprodigy** [comment]
Will need to look over it in the weekend

**Comment by danicasati** [comment]
I confirm the issue:
- Testing with Woocommerce 3.x version, I get error 500 rendering product page where I'm using this plugin.

**Comment by danicasati** [comment]
Any roadmap about this issue?

**Comment by danicasati** [comment]
Please, any roadmap?
I really need to fix this error on my production site...

**Comment by WPprodigy** [comment]
Going to look into this when I have some time over a weekend.

A 500 error indicates something is going wrong at the server level, but is quite generic. Enable error logging and see what more information you can get as to what is going wrong. May lead you to the error/solution.

**Comment by danicasati** [comment]
Using DEBUG mode, I get these errors:

Fatal error: Uncaught exception 'WC_API_Client_HTTP_Exception' with message 'Invalid JSON returned for //XXXX/tienda/wc-api/v2/products?filter%5Blimit%5D=999&consumer_key=ck_3282d53489cc3f8dd36132c46dac59d83e37e4ee&consumer_secret=cs_158dc71e335227eac73d953fc3c959e0d817d777.' in /var/www/vhosts/XXXX/httpdocs/wp-content/plugins/woocommerce-external-product-embed/classes/API-Client-Library/woocommerce-api/class-wc-api-client-http-request.php:182 Stack trace: #0 /var/www/vhosts/XXXX/httpdocs/wp-content/plugins/woocommerce-external-product-embed/classes/API-Client-Library/woocommerce-api/class-wc-api-client.php(286): WC_API_Client_HTTP_Request->dispatch() #1 /var/www/vhosts/XXXX/httpdocs/wp-content/plugins/woocommerce-external-product-embed/classes/API-Client-Library/woocommerce-api/resources/abstract-wc-api-client-resource.php(122): WC_API_Client->make_api_call('GET', 'products', Array) #2 /var/www/vhosts/XXXX/httpdocs/wp-content/plugins/woocomme in /var/www/vhosts/XXXX/httpdocs/wp-content/plugins/woocommerce-external-product-embed/classes/API-Client-Library/woocommerce-api/class-wc-api-client-http-request.php on line 182

**Comment by WPprodigy** [comment]
Make sure there isn't a plugin/theme conflict on the website where the products are coming from, or on the website where you are listing the products. Looks like the API request is returning invalid data.

Disable every but WooCommerce on first site, and switch to a default theme. Then test again, etc.

**Comment by danicasati** [comment]
I've checked in different themes (Hueman, Virtue...) and I can't deactivate plugins because of site production.

**Comment by WPprodigy** [comment]
Did some testing, the plugin is working for me - no errors are logged either. The site where the products are coming form is running the latest version of WooCommerce. 

Something on your external site is causing a conflict in the api.
