### ISSUE TITLE
Error when entering credentials

### ISSUE THREAD

**Issue by fluxeddigital** [WPprodigy/woocommerce-external-product-embed#16]
Hi,

First of, this looks like a great plugin, but im having a big problem with it.

When I enter the API credentials into the settings page of your plugin, it produces this error upon saving them: API Connection Error. Check the Consumer Secret.

<img width="1497" alt="screen shot 2017-12-16 at 19 20 09" src="https://user-images.githubusercontent.com/33608146/34073663-2cc8cdd0-e296-11e7-88a9-a279d9785328.png">

The site running Woocommerce is currently on the latest release.

To troubleshoot, I have done the following:

Revoked & regenerated API Keys.
Uninstalled & reinstalled your plugin.

Please can you help me with a fix?

**Comment by WPprodigy** [comment]
That means the server is returning a `[woocommerce_rest_authentication_error]` error.

If you are 100% certain the keys you are entering are valid, along with the site address, then there must be something interferring with the REST API.

Try temporarily disabling all plugins except for WooCommerce on the external site.
