### ISSUE TITLE
multicurrency eshop. 

### ISSUE THREAD

**Issue by queeckee** [WPprodigy/woocommerce-external-product-embed#17]
Hi is it somehow possible to change the default eshop currency for displayed products? i have the multidomain, multilanguage and multicurrency shop setup with polylang, woocomerce polylang integration and other plugin for currency switch on frontend, but those settings are not displayed for api call.

it would be easiest to set the currency shortcode in shortcode call for example, but how.

**Comment by WPprodigy** [comment]
This will require some customization on your part.

First, you will need to check to see if the multi-currency product is exposing it's settings to the rest api. If not, this won't be possible until that is done.

Then, you will need to request the extra information from the api for each product: https://github.com/WPprodigy/woocommerce-external-product-embed/blob/master/classes/class-wcepe-api-client.php#L81

And lastly, you'll need to pass the new attributes into the template.
