### ISSUE TITLE
Vendor folder

### ISSUE THREAD

**Issue by remondevries** [WPprodigy/woocommerce-external-product-embed#20]
I am trying your plugin, but in file "woocommerce-external-product-embed.php" on line "54" it wants to include "/vendor/autoload.php" but this is no located in the repo. As a result we cannot run it without errors. Or am I doing something wrong? Thanks in advance!

**Comment by WPprodigy** [comment]
Need to install the dev dependencies: https://github.com/WPprodigy/woocommerce-external-product-embed#development

Else DL the release: https://github.com/WPprodigy/woocommerce-external-product-embed/releases
