### ISSUE TITLE
Not Working Anymore

### ISSUE THREAD

**Issue by MoeMauhphie** [WPprodigy/woocommerce-external-product-embed#22]
Hi Caleb,

Just wanted to let you know that this plugin has stopped working, since the recent update of WOOCOMMERCE. It shows nothing anymore. 

Regards,

**Comment by MoeMauhphie** [comment]
Hi Caleb,

Just wanted to know if you're planning to update this plugin? I'd really appreciate it if you could let me know.


Best Regards,
Moe

**Comment by WPprodigy** [comment]
I'm not sure when I will have time to take a look. Do you see any PHP errors after enabling wp debug mode and logging? - https://codex.wordpress.org/Debugging_in_WordPress

Also just to make sure, try temporarily disabling plugins (perhaps on both sides) to ensure there isn't another conflict occurring.

**Comment by MoeMauhphie** [comment]
Thanks for your reply Caleb,

I turned on the debug mode and didn't notice any errors. There were only some notices with regard to the theme. I'm pretty sure it has something to do with Woocommerce recent updates.


Regards,

**Comment by MoeMauhphie** [comment]
I'm really sorry, I made a stupid mistake. Actually it was a JS conflict which is now sorted out. Sorry. It's working like a charm.

Regards,

**Comment by WPprodigy** [comment]
All good :). Thanks for checking back in to let me know.
