### ISSUE TITLE
The site is experiencing technical difficulties.

### ISSUE THREAD

**Issue by educatedmanuel** [WPprodigy/woocommerce-external-product-embed#30]
Hi!

If I add a shortcode to a page the page breaks and I get the message "The site is experiencing technical difficulties." I tried it on another WordPress installation but same issue.

What could be the reason for that?

**Comment by WPprodigy** [comment]
What errors are you seeing in the error logs?

If possible, you can enable wp_debug like this: https://wordpress.org/support/article/debugging-in-wordpress/#wp_debug. Else could ask the web host what PHP errors are being triggered.

Also, make sure you downloaded a release and not the `master` branch in Github: https://github.com/WPprodigy/woocommerce-external-product-embed/releases

**Comment by educatedmanuel** [comment]
Thanks for the quick answer! 

Actually I made the mistake to download the master instead of the of a release. Works now! Thanks!
