### ISSUE TITLE
Feature request: make $opening, $closing and $default_atts overridable from within product-content.php 

### ISSUE THREAD

**Issue by stgoos** [WPprodigy/woocommerce-external-product-embed#37]
Firstly - I just love your plugin as it saved me of inventing the wheel myself (and writing plugins like these are not my daily cup of tea so to speak)!

During my implementation I experienced the need to tailor the `$opening` and `$closing` sections so it blends nicely in within the theme I use (and use case). The same is also applicable for the `$default_atts`. All 3 variables are within `class-wcepe-shortcodes.php`.

Would it be possible to make those 3 variable overridable from the `product-content.php` file which one can add to the (child) theme folder?

Thanks!

--

Some background on my use case: I'm overhauling a Multisite installation for a group of whisky enthusiasts who buy some casks together. The website is split into 3 sections, each with it's own purpose: 1) main info + Newsletter, 2) the WC shop, 3) a wpForo forum. Within the main info site I use wcepe to display a summary of the products (cask info, mostly product attributes). Within the wpForo forum I use it to include a table with all the product (cask) details to the first post of a topic. So in both cases the template and the defaults are different.

**Comment by WPprodigy** [comment]
Can't put the opening/closing markup into `product-content.php` since this file is repeated for each item, but there are filters available to customize: https://github.com/WPprodigy/woocommerce-external-product-embed/blob/dc69e4840f67014593a9c42d9483d6dd7f4941bf/classes/class-wcepe-shortcodes.php#L106-L107

So in your theme's functions.php for example:

```
add_filter( 'wcepe_products_loop_wrapper_open', function( $markup, $atts ) {
	return '<div class="woocommerce wcepe_products_wrap columns-' . $atts['columns'] . '"><ul class="wcepe_products products">';
} );
```

**Comment by stgoos** [comment]
Okay - sweet!! I like that and learned something in the process too about the apply_filters() stuff :)

Especially those $opening and $closing overrides where on my wishlist. Doing it from a functions.php is totally fine with me. Thanks for the explanation and example, I'll will check it out on my server later today.

I'll close this topic as the feature request is already built in.
