### ISSUE TITLE
Uncaught Error: Class 'Automattic\WooCommerce\Client' not found

### ISSUE THREAD

**Issue by ghost** [WPprodigy/woocommerce-external-product-embed#41]
Hi
I get error when trying to use a plugin. I use WordPress version 5.7.1

Une erreur de type E_ERROR a été causée dans la ligne 33 du fichier /home/bwt/webapps/BWT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-api-client.php. Message d’erreur : Uncaught Error: Class 'Automattic\WooCommerce\Client' not found in /home/bwt/webapps/BWT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-api-client.php:33
Stack trace:
#0 /home/bwt/webapps/BWT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-api-client.php(45): WCEPE_API_Client->connect()
#1 /home/bwt/webapps/BWT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-admin.php(240): WCEPE_API_Client->test_connection()
#2 /home/bwt/webapps/BWT/wp-includes/class-wp-hook.php(292): WCEPE_Admin::test_api_connection()
#3 /home/bwt/webapps/BWT/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#4 /home/bwt/webapps/BWT/wp-includes/plugin.php(484): WP_Hook->do_action()
#5 /home/bwt/webapps/BWT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-admin.php(199): do_action()
#6 /home/bwt/webapps/BWT/wp-includes/class-wp-hook.php(292): WCEPE_Admin::wcepe_options_page()
#7 /home/bwt/webapps/BWT/

**Comment by ghost** [comment]
Solve

**Comment by stgoos** [comment]
@sonyflagel how did you resolve the issue you experienced?

**Comment by WPprodigy** [comment]
Make sure you downloaded a release and not the master branch in Github: https://github.com/WPprodigy/woocommerce-external-product-embed/releases

Otherwise need to follow these steps: https://github.com/WPprodigy/woocommerce-external-product-embed#development
