### ISSUE TITLE
Feature request:  post_author

### ISSUE THREAD

**Issue by bentasm1** [WPprodigy/woocommerce-external-product-embed#7]
If you can add a post_author query, then you can also start hooking into WC Vendors for multi vendor marketplaces.  Quite a useful feature to add.  Simply doing post_author="xx" where xx is ID, and you'd make a lot of our members happy. :-)

**Comment by bentasm1** [comment]
https://www.wcvendors.com/help/topic/external-product-list-adverts/

**Comment by WPprodigy** [comment]
Interesting. I'll look into adding that :)

**Comment by WPprodigy** [comment]
WooCommerce doesn't do much with authors by default (products hide the option), so it doesn't seem to be possible to get a list of products using post_author with the current version of the API: http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products. Would require some customization on the WC side, something this plugin doesn't have control over.

But I will keep an eye out for this to be a filtering option.
