### ISSUE TITLE
Fatal error: Uncaught exception 'WC_API_Client_HTTP_Exception' with message 'Invalid JSON returned

### ISSUE THREAD

**Issue by annakyn** [WPprodigy/woocommerce-external-product-embed#8]
Not getting very far with this plugin, although I love the concept so hoping to stick with it! Getting this error running WP 4.3.1 and WC 2.4.10. Any help appreciated.

**Comment by BurlesonBrad** [comment]
Yo @annakyn I need someone else to test @WPprodigy 's plugin with.  Wanna swap API keys with each other?

**Comment by annakyn** [comment]
Yeah could do that. I assume only read access is needed for the plugin?

**Comment by BurlesonBrad** [comment]
Not sure.  Let me run get the kids at school and I'll fire it up :+1:

**Comment by BurlesonBrad** [comment]
Looks to me like it'd be read only:

https://github.com/WPprodigy/woocommerce-external-product-embed/blob/efedf84b5ce3e753211912334405c30886d67b1e/classes/class-woocommerce-external-product-embed-admin.php#L64-L74

**Comment by annakyn** [comment]
I'll drop you a mail with the API keys.

**Comment by annakyn** [comment]
Actually, think I'm having trouble as it's a multi-vendor site- the admin with the api keys doesn't have any products associated. so you're probably best setting up a test site instead to trial with.

**Comment by WPprodigy** [comment]
Hey Guys,

Make sure the shortcode is not using Smart Quotes. I see that the readme file has those evil things in  it - I'll be updating that shortly. Just go to the text editor in WordPress and re-type all the quotes.

The "Fatal error: Uncaught exception 'WC_API_Client_HTTP_Exception' with message 'Invalid JSON returned " error is coming from the WooCommerce site's side of things. Something (plugin or theme) is causing the api to return invalid data. Try temporarily disabling all plugins and then try to make a connection with the shortcode on another site.

**Comment by annakyn** [comment]
Thanks, if I can find the conflict I will post up.

**Comment by WPprodigy** [comment]
I'm working on some enhancements for this plugin today, so there should be some commits coming through shortly. Let me know what/if you find the cause of your error, so i can adjust things accordingly :).

Also, is your site on http or https? I haven't been able to test ssl certified sites yet, and I'm guessing there might be a problem there. (Note: The SSL matters on the WooCommerce site, not on the site that is embedding products).

**Comment by WPprodigy** [comment]
@BurlesonBrad: For testing, you can use a localhost site for this plugin. Just make sure the site running WooCommerce is a live site.
